version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-ip-geolocation-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11i3h2ijp8f6n"
s3_prefix = "sam-ip-geolocation-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
